### PR TITLE
CI

### PR DESCRIPTION
**Pull request by zhihaoy**
- add `CMakeSettings.json` for Visual Studio
- support WSL-GCC build
- setup a basic CI using GitHub Actions

### CODE REVIEW

**Comment by zhihaoy** [comment]
Not sure why this PR doesn't trigger a CI cicle. What should happen is this https://github.com/zhihaoy/polyfill-23/runs/4848082017 (maybe because it has run once on this commit?)

**Comment by Love69by** [comment]
우리는 하나이다.

**Comment by Love69by** [comment]
웃으면 복이와요

**Comment by zhihaoy** [comment]
Should be good now.

**Comment by hanickadot** [comment]
Why are you adding <functional> ?

**Comment by hanickadot** [comment]
Why are you adding `<functional>`?

**Comment by zhihaoy** [comment]
GCC 11.1:
```
move_only_function.hpp:2202:37: note: ‘std::invoke’ is defined in header ‘<functional>’; did you forget to ‘#include <functional>’?
```

**Review by hanickadot — APPROVED** [review]

**Comment by hanickadot** [comment]
Thank you for PR! Would be possible to add clang 13 too?

**Comment by zhihaoy** [comment]
> Thank you for PR! Would be possible to add clang 13 too?

Sent #2 to add AppleClang 13, which is probably Clang/LLVM 12. But it works :)

**Pull request merged**
